update to cuda 12.9.1

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -4,9 +4,9 @@ on:
   workflow_dispatch:
   #push:
   #  branches: [ "main" ]
-    
+
 env:
-  UBUNTU_VERSION: 22.04
+  UBUNTU_VERSION: 24.04
   BUILDX_NO_DEFAULT_ATTESTATIONS: 1
 
 jobs:
@@ -16,10 +16,14 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1"}
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+            }
     steps:
-      -
-        name: Free Space
+      - name: Free Space
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -29,61 +33,54 @@ jobs:
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           df -h
-      -
-        name: Env Setter
+      - name: Env Setter
         run: |
           REPO=${GITHUB_REPOSITORY,,}
           echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
           echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Permissions fixes
+      - name: Permissions fixes
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
+      - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
+          password: ${{ secrets.GH_TOKEN }}
+      - name: Set tags
         run: |
-            img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            if [[ -z '${{ matrix.build.comfyui }}' ]]; then
-                COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
-            else
-                COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
-            fi
-            [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
+          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
+          if [[ -z '${{ matrix.build.comfyui }}' ]]; then
+              COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
+          else
+              COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
+          fi
+          [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+          echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
 
-            base_tag="v2-cpu-${{ env.UBUNTU_VERSION }}"
+          base_tag="v2-cpu-${{ env.UBUNTU_VERSION }}"
 
-            if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                echo "Marking latest"
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
-            else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
-            fi
-            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
+          if [[ ${{ matrix.build.latest }} == "true" ]]; then
+              echo "Marking latest"
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
+          else
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
+          fi
+          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
           build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cpu-${{ env.UBUNTU_VERSION }}
+            IMAGE_BASE=ghcr.io/starforge-ai/python:${{ matrix.build.python }}-v2-cpu-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
             COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
@@ -91,18 +88,64 @@ jobs:
           # Avoids unknown/unknown architecture and extra metadata
           provenance: false
           tags: ${{ env.TAGS }}
-    
+
   nvidia-base:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-base"}
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-cudnn8-devel"}
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "13.1.0-base",
+            }
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "13.0.2-base",
+            }  
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "13.0.2-cudnn-runtime",
+            }  
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "13.0.2-cudnn-devel",
+            }
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "12.9.1-base",
+            }  
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "12.9.1-cudnn-runtime",
+            }  
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              cuda: "12.9.1-cudnn-devel",
+            }
     steps:
-      -
-        name: Free Space
+      - name: Free Space
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -112,35 +155,29 @@ jobs:
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           df -h
-      -
-        name: Env Setter
+      - name: Env Setter
         run: |
           REPO=${GITHUB_REPOSITORY,,}
           echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
           echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Permissions fixes
+      - name: Permissions fixes
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
+      - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
+          password: ${{ secrets.GH_TOKEN }}
+      - name: Set tags
         run: |
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
@@ -168,13 +205,12 @@ jobs:
                 TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}-devel"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
           build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
+            IMAGE_BASE=ghcr.io/starforge-ai/python:${{ matrix.build.python }}-v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
             COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
@@ -188,10 +224,15 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.3.1", rocm: "6.0-runtime"}
+          - {
+              latest: "false",
+              comfyui: "v0.8.1",
+              python: "3.11",
+              pytorch: "2.9.0",
+              rocm: "7.0.3-runtime",
+            }
     steps:
-      -
-        name: Free Space
+      - name: Free Space
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -201,65 +242,58 @@ jobs:
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           df -h
-      -
-        name: Env Setter
+      - name: Env Setter
         run: |
           REPO=${GITHUB_REPOSITORY,,}
           echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
           echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Permissions fixes
+      - name: Permissions fixes
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
+      - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
+          password: ${{ secrets.GH_TOKEN }}
+      - name: Set tags
         run: |
-            img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
-            if [[ -z '${{ matrix.build.comfyui }}' ]]; then
-                COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
-            else
-                COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
-            fi
-            [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
+          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
+          img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
+          if [[ -z '${{ matrix.build.comfyui }}' ]]; then
+              COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
+          else
+              COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
+          fi
+          [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+          echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
 
-            base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
+          base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
 
-            if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                echo "Marking latest"
-                # GHCR.io Tags
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
-                # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}, ${img_path_dhub}:latest"
-            else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
-            fi
-            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
+          if [[ ${{ matrix.build.latest }} == "true" ]]; then
+              echo "Marking latest"
+              # GHCR.io Tags
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+              # Docker.io Tags
+              TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}, ${img_path_dhub}:latest"
+          else
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
+          fi
+          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
           build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
+            IMAGE_BASE=ghcr.io/starforge-ai/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
             COMFYUI_BUILD_REF=${{ env.COMFYUI_BUILD_REF }}
